USE rowdys_closet_db;

DELETE FROM products;

INSERT INTO products (price, size, name, stock, type, description , img_file_path)
VALUES
    (42.00, "Large", "UTSA Roadrunnner Head Hoodie", 35, "Hoodies", "This cozy hooded sweatshirt will keep you warm when the weather is not. Comfortable and versatile, it is great for lounging around or life on the go.", "/static/img/product_images/UTSA_Roadrunnner_Head_Hoodie.png"),
    (42.00, "Large", "UTSA Hoodie", 25, "Hoodies", "This cozy hooded sweatshirt will keep you warm when the weather is not. Comfortable and versatile, it is great for lounging around or life on the go.", "/static/img/product_images/UTSA_Hoodie.png"),
    (42.00, "Large", "UTSA Football Verticle Hoodie", 25, "Hoodies", "This cozy hooded sweatshirt will keep you warm when the weather is not. Comfortable and versatile, it is great for lounging around or life on the go.", "/static/img/product_images/UTSA_Football_Vertical_Hoodie.png"),
    (42.00, "Large", "UTSA Hoodie", 25, "Hoodies", "This cozy hooded sweatshirt will keep you warm when the weather is not. Comfortable and versatile, it is great for lounging around or life on the go.", "/static/img/product_images/UTSA_Hoodie.png"),
    (42.00, "Large", "UTSA Ugly Christmas Sweater", 25, "Hoodies", "This cozy hooded sweatshirt will keep you warm when the weather is not. Comfortable and versatile, it is great for lounging around or life on the go.", "/static/img/product_images/UTSA_Ugly_Christmas_Sweater.png"),
    (42.00, "Large", "UTSA Roadrunner Head - Full Zip Hoodie", 25, "Hoodies", "This cozy hooded sweatshirt will keep you warm when the weather isn't. Comfortable and versatile, it's great for lounging around or life on the go.", "/static/img/product_images/UTSA_Roadrunner_Head_-_Full_Zip_Hoodie.png"),
    (57.00, "Large", "UTSA Full Mascot Vintage Sweatshirt", 25, "Hoodies", "Ooh la la. Certified organic cotton makes these French terry beauties 100% comfortable. Plus, helping save the environment is always a good look.", "/static/img/product_images/UTSA_Full_Mascot_Vintage_Sweater.png"),
    (57.00, "Large", "UTSA Script Vintage", 25, "Hoodies", "Ooh la la. Certified organic cotton makes these French terry beauties 100% comfortable. Plus, helping save the environment is always a good look.", "/static/img/product_images/UTSA_Script_Vintage.png"),
    (58.00, "Large", "UTSA Softshell Core Vest", 25, "Jackets", "Versatile enough to be layered for four seasons of wear, this windproof and virtually waterproof vest is ideal for active pursuits when you need to protect your core from the wind.", "/static/img/product_images/UTSA_Softshell_Core_Vest.png"),
    (68.00, "Large", "UTSA Black Charger Jacket", 25, "Jackets", "A wear-anywhere heavyweight jacket. Built to charge through mild wind and rain, our Heavyweight Charger Jacket features a water-resistant shell and warm fleece body lining for year-round versatility.", "/static/img/product_images/UTSA_Black_Charger_Jacket.png"),
    (64.00, "Large", "UTSA Black Softshell Jacket", 25, "Jackets", "Ready for layering, this stylish full-zip jacket will keep you warm and dry - and looking good, too. Comfortable and cozy, it's perfect for those days when the weather just can't slow you down.", "/static/img/product_images/UTSA_Black_Softshell_Jacket.png"),
    (155.00, "Large", "UTSA Black Heather Jacket", 25, "Jackets", "A soft, heathered tone adds casual appeal to the heavyweight, sweater-knit fleece jacket that's warm, yet breathable, on the trails.", "/static/img/product_images/UTSA_Black_Heather_Jacket.png"),
    (310.00, "Large", "UTSA Black Thermoball Trekker Jacket", 15, "Jackets", "Designed with baffles contoured to fit your body, this streamlined jacket offers lightweight, highly compressible ThermoBall™ powered by PrimaLoft® synthetic insulation. Excellent at retaining loft and warmth even when wet, the ThermoBall™ Trekker Jacket will keep you warmer regardless of the conditions.", "/static/img/product_images/UTSA_Black_Thermoball_Trekker_Jacket.png"),
    (230.00, "Large", "UTSA Black Apex Barrier Softwhell Jacket", 25, "Jackets", "Windproof with plenty of stretch, this iconic heavyweight soft shell offers the ultimate in weather protection. The coveted Apex Barrier Soft Shell stops rain and wind to keep you warm and dry. A brushed fleece interior ensures all-day comfort.", "/static/img/product_images/UTSA_Black_Apex_Barrier_Softwhell_Jacket.png"),
    (57.00, "Large", "UTSA Sport Tek Sport Wick Stretch Jacket", 25, "Jackets", "Ideal for year round layering, our pullover is a true performance piece for running, yoga or just hanging out. Extra stretchy, this pullover has a soft brushed backing and features Sport Wick moisture wicking technology for comfort.", "/static/img/product_images/UTSA_Sport_Tek_Sport_Wick_Stretch_Jacket.png"),
    (170.00, "Large", "UTSA Black Vortex Waterproof 3 in 1 Jacket", 25, "Jackets", "Packed with weather-fighting features, the Vortex Waterproof 3-in-1 provides a completely versatile outerwear system in one jacket. The fully seam-sealed waterproof shell and the warm polyfilled inner jacket can be worn separately or combined for optimal warmth and protection.", "/static/img/product_images/UTSA_Black_Vortex_Waterproof_3_in_1_Jacket.png"),
    (22.00, "Large", "UTSA Roadrunner Head T-Shirt", 25, "T-Shirts", "This practical, basic t shirt can be layered or worn alone. You can never have too many of these versatile shirts in your closet. Just toss one on and go.", "/static/img/product_images/UTSA_Roadrunner_Head_T-Shirt.png"),
    (22.00, "Large", "UTSA Logo T-Shirt", 25, "T-Shirts", "This practical, basic t shirt can be layered or worn alone. You can never have too many of these versatile shirts in your closet. Just toss one on and go.", "/static/img/product_images/UTSA_Logo_T-Shirt.png"),
    (22.00, "Large", "UTSA Roadrunner Arched T-Shirt", 25, "T-Shirts", "This practical, basic t shirt can be layered or worn alone. You can never have too many of these versatile shirts in your closet. Just toss one on and go.", "/static/img/product_images/UTSA_Roadrunner_Arched_T-Shirt.png"),
    (22.00, "Large", "UTSA Ugly Christmas T-Shirt", 25, "T-Shirts", "This practical, basic t shirt can be layered or worn alone. You can never have too many of these versatile shirts in your closet. Just toss one on and go.", "/static/img/product_images/UTSA_Ugly_Christmas_T-Shirt.png"),
    (22.00, "Large", "UTSA Women's Basketball Runners T-Shirt", 25, "T-Shirts", "This practical, basic t shirt can be layered or worn alone. You can never have too many of these versatile shirts in your closet. Just toss one on and go.", "/static/img/product_images/UTSA_Womens_Basketball_Runners_T-Shirt.png"),
    (22.00, "Large", "UTSA Fifteenth T-Shirt", 25, "T-Shirts", "This practical, basic t shirt can be layered or worn alone. You can never have too many of these versatile shirts in your closet. Just toss one on and go.", "/static/img/product_images/UTSA_Fifteenth_T-Shirt.png"),
    (22.00, "Large", "UTSA Baseball T-Shirt", 25, "T-Shirts", "This practical, basic t shirt can be layered or worn alone. You can never have too many of these versatile shirts in your closet. Just toss one on and go.", "/static/img/product_images/UTSA_Baseball_T-Shirt.png"),
    (22.00, "Large", "UTSA Performance Tee", 25, "T-Shirts", "This practical, basic t shirt can be layered or worn alone. You can never have too many of these versatile shirts in your closet. Just toss one on and go.", "/static/img/product_images/UTSA_Performance_Tee.png"),
    (42.00, "Medium", "UTSA Roadrunnner Head Hoodie", 35, "Hoodies", "This cozy hooded sweatshirt will keep you warm when the weather is not. Comfortable and versatile, it is great for lounging around or life on the go.", "/static/img/product_images/UTSA_Roadrunnner_Head_Hoodie.png"),
    (42.00, "Medium", "UTSA Hoodie", 25, "Hoodies", "This cozy hooded sweatshirt will keep you warm when the weather is not. Comfortable and versatile, it is great for lounging around or life on the go.", "/static/img/product_images/UTSA_Hoodie.png"),
    (42.00, "Medium", "UTSA Football Verticle Hoodie", 25, "Hoodies", "This cozy hooded sweatshirt will keep you warm when the weather is not. Comfortable and versatile, it is great for lounging around or life on the go.", "/static/img/product_images/UTSA_Football_Vertical_Hoodie.png"),
    (42.00, "Medium", "UTSA Hoodie", 25, "Hoodies", "This cozy hooded sweatshirt will keep you warm when the weather is not. Comfortable and versatile, it is great for lounging around or life on the go.", "/static/img/product_images/UTSA_Hoodie.png"),
    (42.00, "Medium", "UTSA Ugly Christmas Sweater", 25, "Hoodies", "This cozy hooded sweatshirt will keep you warm when the weather is not. Comfortable and versatile, it is great for lounging around or life on the go.", "/static/img/product_images/UTSA_Ugly_Christmas_Sweater.png"),
    (42.00, "Medium", "UTSA Roadrunner Head - Full Zip Hoodie", 25, "Hoodies", "This cozy hooded sweatshirt will keep you warm when the weather isn't. Comfortable and versatile, it's great for lounging around or life on the go.", "/static/img/product_images/UTSA_Roadrunner_Head_-_Full_Zip_Hoodie.png"),
    (57.00, "Medium", "UTSA Full Mascot Vintage Sweatshirt", 25, "Hoodies", "Ooh la la. Certified organic cotton makes these French terry beauties 100% comfortable. Plus, helping save the environment is always a good look.", "/static/img/product_images/UTSA_Full_Mascot_Vintage_Sweater.png"),
    (57.00, "Medium", "UTSA Script Vintage", 25, "Hoodies", "Ooh la la. Certified organic cotton makes these French terry beauties 100% comfortable. Plus, helping save the environment is always a good look.", "/static/img/product_images/UTSA_Script_Vintage.png"),
    (58.00, "Medium", "UTSA Softshell Core Vest", 25, "Jackets", "Versatile enough to be layered for four seasons of wear, this windproof and virtually waterproof vest is ideal for active pursuits when you need to protect your core from the wind.", "/static/img/product_images/UTSA_Softshell_Core_Vest.png"),
    (68.00, "Medium", "UTSA Black Charger Jacket", 25, "Jackets", "A wear-anywhere heavyweight jacket. Built to charge through mild wind and rain, our Heavyweight Charger Jacket features a water-resistant shell and warm fleece body lining for year-round versatility.", "/static/img/product_images/UTSA_Black_Charger_Jacket.png"),
    (64.00, "Medium", "UTSA Black Softshell Jacket", 25, "Jackets", "Ready for layering, this stylish full-zip jacket will keep you warm and dry - and looking good, too. Comfortable and cozy, it's perfect for those days when the weather just can't slow you down.", "/static/img/product_images/UTSA_Black_Softshell_Jacket.png"),
    (155.00, "Medium", "UTSA Black Heather Jacket", 25, "Jackets", "A soft, heathered tone adds casual appeal to the heavyweight, sweater-knit fleece jacket that's warm, yet breathable, on the trails.", "/static/img/product_images/UTSA_Black_Heather_Jacket.png"),
    (310.00, "Medium", "UTSA Black Thermoball Trekker Jacket", 15, "Jackets", "Designed with baffles contoured to fit your body, this streamlined jacket offers lightweight, highly compressible ThermoBall™ powered by PrimaLoft® synthetic insulation. Excellent at retaining loft and warmth even when wet, the ThermoBall™ Trekker Jacket will keep you warmer regardless of the conditions.", "/static/img/product_images/UTSA_Black_Thermoball_Trekker_Jacket.png"),
    (230.00, "Medium", "UTSA Black Apex Barrier Softwhell Jacket", 25, "Jackets", "Windproof with plenty of stretch, this iconic heavyweight soft shell offers the ultimate in weather protection. The coveted Apex Barrier Soft Shell stops rain and wind to keep you warm and dry. A brushed fleece interior ensures all-day comfort.", "/static/img/product_images/UTSA_Black_Apex_Barrier_Softwhell_Jacket.png"),
    (57.00, "Medium", "UTSA Sport Tek Sport Wick Stretch Jacket", 25, "Jackets", "Ideal for year round layering, our pullover is a true performance piece for running, yoga or just hanging out. Extra stretchy, this pullover has a soft brushed backing and features Sport Wick moisture wicking technology for comfort.", "/static/img/product_images/UTSA_Sport_Tek_Sport_Wick_Stretch_Jacket.png"),
    (170.00, "Medium", "UTSA Black Vortex Waterproof 3 in 1 Jacket", 25, "Jackets", "Packed with weather-fighting features, the Vortex Waterproof 3-in-1 provides a completely versatile outerwear system in one jacket. The fully seam-sealed waterproof shell and the warm polyfilled inner jacket can be worn separately or combined for optimal warmth and protection.", "/static/img/product_images/UTSA_Black_Vortex_Waterproof_3_in_1_Jacket.png"),
    (22.00, "Medium", "UTSA Roadrunner Head T-Shirt", 25, "T-Shirts", "This practical, basic t shirt can be layered or worn alone. You can never have too many of these versatile shirts in your closet. Just toss one on and go.", "/static/img/product_images/UTSA_Roadrunner_Head_T-Shirt.png"),
    (22.00, "Medium", "UTSA Logo T-Shirt", 25, "T-Shirts", "This practical, basic t shirt can be layered or worn alone. You can never have too many of these versatile shirts in your closet. Just toss one on and go.", "/static/img/product_images/UTSA_Logo_T-Shirt.png"),
    (22.00, "Medium", "UTSA Roadrunner Arched T-Shirt", 25, "T-Shirts", "This practical, basic t shirt can be layered or worn alone. You can never have too many of these versatile shirts in your closet. Just toss one on and go.", "/static/img/product_images/UTSA_Roadrunner_Arched_T-Shirt.png"),
    (22.00, "Medium", "UTSA Ugly Christmas T-Shirt", 25, "T-Shirts", "This practical, basic t shirt can be layered or worn alone. You can never have too many of these versatile shirts in your closet. Just toss one on and go.", "/static/img/product_images/UTSA_Ugly_Christmas_T-Shirt.png"),
    (22.00, "Medium", "UTSA Women's Basketball Runners T-Shirt", 25, "T-Shirts", "This practical, basic t shirt can be layered or worn alone. You can never have too many of these versatile shirts in your closet. Just toss one on and go.", "/static/img/product_images/UTSA_Womens_Basketball_Runners_T-Shirt.png"),
    (22.00, "Medium", "UTSA Fifteenth T-Shirt", 25, "T-Shirts", "This practical, basic t shirt can be layered or worn alone. You can never have too many of these versatile shirts in your closet. Just toss one on and go.", "/static/img/product_images/UTSA_Fifteenth_T-Shirt.png"),
    (22.00, "Medium", "UTSA Baseball T-Shirt", 25, "T-Shirts", "This practical, basic t shirt can be layered or worn alone. You can never have too many of these versatile shirts in your closet. Just toss one on and go.", "/static/img/product_images/UTSA_Baseball_T-Shirt.png"),
    (22.00, "Medium", "UTSA Performance Tee", 25, "T-Shirts", "This practical, basic t shirt can be layered or worn alone. You can never have too many of these versatile shirts in your closet. Just toss one on and go.", "/static/img/product_images/UTSA_Performance_Tee.png"),
    (42.00, "Small", "UTSA Roadrunner Head - Full Zip Hoodie", 25, "Hoodies", "This cozy hooded sweatshirt will keep you warm when the weather isn't. Comfortable and versatile, it's great for lounging around or life on the go.", "/static/img/product_images/UTSA_Roadrunner_Head_-_Full_Zip_Hoodie.png"),
    (57.00, "Small", "UTSA Full Mascot Vintage Sweatshirt", 25, "Hoodies", "Ooh la la. Certified organic cotton makes these French terry beauties 100% comfortable. Plus, helping save the environment is always a good look.", "/static/img/product_images/UTSA_Full_Mascot_Vintage_Sweater.png"),
    (57.00, "Small", "UTSA Script Vintage", 25, "Hoodies", "Ooh la la. Certified organic cotton makes these French terry beauties 100% comfortable. Plus, helping save the environment is always a good look.", "/static/img/product_images/UTSA_Script_Vintage.png"),
    (58.00, "Small", "UTSA Softshell Core Vest", 25, "Jackets", "Versatile enough to be layered for four seasons of wear, this windproof and virtually waterproof vest is ideal for active pursuits when you need to protect your core from the wind.", "/static/img/product_images/UTSA_Softshell_Core_Vest.png"),
    (68.00, "Small", "UTSA Black Charger Jacket", 25, "Jackets", "A wear-anywhere heavyweight jacket. Built to charge through mild wind and rain, our Heavyweight Charger Jacket features a water-resistant shell and warm fleece body lining for year-round versatility.", "/static/img/product_images/UTSA_Black_Charger_Jacket.png"),
    (64.00, "Small", "UTSA Black Softshell Jacket", 25, "Jackets", "Ready for layering, this stylish full-zip jacket will keep you warm and dry - and looking good, too. Comfortable and cozy, it's perfect for those days when the weather just can't slow you down.", "/static/img/product_images/UTSA_Black_Softshell_Jacket.png"),
    (155.00, "Small", "UTSA Black Heather Jacket", 25, "Jackets", "A soft, heathered tone adds casual appeal to the heavyweight, sweater-knit fleece jacket that's warm, yet breathable, on the trails.", "/static/img/product_images/UTSA_Black_Heather_Jacket.png"),
    (310.00, "Small", "UTSA Black Thermoball Trekker Jacket", 15, "Jackets", "Designed with baffles contoured to fit your body, this streamlined jacket offers lightweight, highly compressible ThermoBall™ powered by PrimaLoft® synthetic insulation. Excellent at retaining loft and warmth even when wet, the ThermoBall™ Trekker Jacket will keep you warmer regardless of the conditions.", "/static/img/product_images/UTSA_Black_Thermoball_Trekker_Jacket.png"),
    (230.00, "Small", "UTSA Black Apex Barrier Softwhell Jacket", 25, "Jackets", "Windproof with plenty of stretch, this iconic heavyweight soft shell offers the ultimate in weather protection. The coveted Apex Barrier Soft Shell stops rain and wind to keep you warm and dry. A brushed fleece interior ensures all-day comfort.", "/static/img/product_images/UTSA_Black_Apex_Barrier_Softwhell_Jacket.png"),
    (57.00, "Small", "UTSA Sport Tek Sport Wick Stretch Jacket", 25, "Jackets", "Ideal for year round layering, our pullover is a true performance piece for running, yoga or just hanging out. Extra stretchy, this pullover has a soft brushed backing and features Sport Wick moisture wicking technology for comfort.", "/static/img/product_images/UTSA_Sport_Tek_Sport_Wick_Stretch_Jacket.png"),
    (170.00, "Small", "UTSA Black Vortex Waterproof 3 in 1 Jacket", 25, "Jackets", "Packed with weather-fighting features, the Vortex Waterproof 3-in-1 provides a completely versatile outerwear system in one jacket. The fully seam-sealed waterproof shell and the warm polyfilled inner jacket can be worn separately or combined for optimal warmth and protection.", "/static/img/product_images/UTSA_Black_Vortex_Waterproof_3_in_1_Jacket.png"),
    (22.00, "Small", "UTSA Roadrunner Head T-Shirt", 25, "T-Shirts", "This practical, basic t shirt can be layered or worn alone. You can never have too many of these versatile shirts in your closet. Just toss one on and go.", "/static/img/product_images/UTSA_Roadrunner_Head_T-Shirt.png"),
    (22.00, "Small", "UTSA Logo T-Shirt", 25, "T-Shirts", "This practical, basic t shirt can be layered or worn alone. You can never have too many of these versatile shirts in your closet. Just toss one on and go.", "/static/img/product_images/UTSA_Logo_T-Shirt.png"),
    (22.00, "Small", "UTSA Roadrunner Arched T-Shirt", 25, "T-Shirts", "This practical, basic t shirt can be layered or worn alone. You can never have too many of these versatile shirts in your closet. Just toss one on and go.", "/static/img/product_images/UTSA_Roadrunner_Arched_T-Shirt.png"),
    (22.00, "Small", "UTSA Ugly Christmas T-Shirt", 25, "T-Shirts", "This practical, basic t shirt can be layered or worn alone. You can never have too many of these versatile shirts in your closet. Just toss one on and go.", "/static/img/product_images/UTSA_Ugly_Christmas_T-Shirt.png"),
    (22.00, "Small", "UTSA Women's Basketball Runners T-Shirt", 25, "T-Shirts", "This practical, basic t shirt can be layered or worn alone. You can never have too many of these versatile shirts in your closet. Just toss one on and go.", "/static/img/product_images/UTSA_Womens_Basketball_Runners_T-Shirt.png"),
    (22.00, "Small", "UTSA Fifteenth T-Shirt", 25, "T-Shirts", "This practical, basic t shirt can be layered or worn alone. You can never have too many of these versatile shirts in your closet. Just toss one on and go.", "/static/img/product_images/UTSA_Fifteenth_T-Shirt.png"),
    (22.00, "Small", "UTSA Baseball T-Shirt", 25, "T-Shirts", "This practical, basic t shirt can be layered or worn alone. You can never have too many of these versatile shirts in your closet. Just toss one on and go.", "/static/img/product_images/UTSA_Baseball_T-Shirt.png"),
    (22.00, "Small", "UTSA Performance Tee", 25, "T-Shirts", "This practical, basic t shirt can be layered or worn alone. You can never have too many of these versatile shirts in your closet. Just toss one on and go.", "/static/img/product_images/UTSA_Performance_Tee.png"),
    (18.00, NULL, "Brushed Bull Denim Visor 210", 55, "Headwear", "Stay focused, cool, and comfortable in this versatile hat that will keep the sun out of your eyes and perspiration at bay. Adjustable closure allows for a perfect fit.", "/static/img/product_images/Brushed_Bull_Denim_Visor_210.png"),
    (21.00, NULL, "Structured Adjustable Pro Style Hat - Mascot", 45, "Headwear", "Classic and relaxed, this pro style hat offers a laid-back medium profile and a flexible fit that will compliment any casual fashion look.", "/static/img/product_images/Structured_Adjustable_Pro_Style_Hat_-_Mascot.png"),
    (21.00, NULL, "Mountain Beanie - UTSA Roadrunner Head - Institutional Mark", 15, "Headwear", "Classic and relaxed, this pro style hat offers a laid-back medium profile and a flexible fit that will compliment any casual fashion look.", "/static/img/product_images/Mountain_Beanie_-_UTSA_Roadrunner_Head.png"),
    (32.00, NULL, "Mountain Beanie - UTSA Roadrunner Head", 20, "Headwear", "Made of 100% recycled fabric, this beanie is made for snow shoveling or just walking in the woods. A fleece liner adds cozy warmth in cold conditions.", "/static/img/product_images/Mountain_Beanie_-_UTSA_Roadrunner_Head.png"),
    (45.00, NULL, "Knit Beanie w:Cuff - UTSA Roadrunner Head", 55, "Headwear", "Soft to the touch, this timeless cap is stretchy rib knit for a stay-put fit.", "/static/img/product_images/Knit_Beanie_Cuff_-_UTSA_Roadrunner_Head.png"),
    (15.00, NULL, "Sportsman Pom Pom Cuffed Beanie", 45, "Headwear", "A cool, modern look that goes way beyond winter. Its as cozy and practical as it is stylish!", "/static/img/product_images/Sportsman_Pom_Pom_Cuffed_Beanie.png"),
    (82.00, NULL, "Black Roam Lite Backpack", 30, "Bags", "Minimalism meets practicality in the Roam Light Backpack. Slim and stylish without sacrificing functionality, this backpack is a compact powerhouse of brand promotion. Featuring two stretch mesh bottle pockets and two exterior-access zipper pockets. Carry-on friendly.", "/static/img/product_images/Black_Roam_Lite_Backpack.png");


SELECT * FROM products


UPDATE products
SET stock = 0
WHERE name = "UTSA Roadrunnner Head Hoodie";














-- Insert all products
